### ISSUE TITLE
发送长短信期望支持直接拆分发送

### ISSUE THREAD

**Issue by igso888** [protocol-laboratory/sms-client-java#15]
我们的产品SMPP服务端支持最大160长度，不支持直接接收长短信，因此client需要支持拆分长短信为多条进行发送。
拆分规则遵循gsm网络标准。

**Comment by hezhangjian** [comment]
Is there any official gsm specific docs?

**Comment by igso888** [comment]
https://www.etsi.org/deliver/etsi_gts/03/0340/05.03.00_60/gsmts_0340v050300p.pdf

**Comment by xiang092689** [comment]
which part is key part of the message transformation in this doc? i'm a little bit confused.

**Comment by hezhangjian** [comment]
closed by #16
